import { randomUUID } from "node:crypto";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { testDatabase, TEST_OWNER } from "@/test/database";
import { createReading, claimNext, readingStatus, queueDocument, retrySegment } from "./jobs";
import { generateNext } from "@/workflows/steps";
import { INDEXTTS_MODEL, indexTtsConfig } from "./tts-config";
import { registerReferenceVoice } from "./reference-voices";
import { webVoices, setWebVoice } from "./web-voices";
import { ownerPrefix, sha256 } from "./blob";
import { recoverDispatches } from "./dispatch";
import { POST as tts } from "@/app/api/tts/route";
import { reserveUpload } from "./uploads";
import type { Voice } from "./types";
const mock = vi.hoisted(() => ({ fetch: vi.fn(), get: vi.fn(), put: vi.fn(), head: vi.fn(), start: vi.fn() }));
vi.mock("@vercel/blob", () => ({ get: mock.get, put: mock.put, head: mock.head }));
vi.mock("@/lib/config", async (original) => ({ ...await original<typeof import("./config")>(), validateResourceIdentity: async () => {} }));
vi.mock("@/lib/auth", () => ({ requireOwner: async () => TEST_OWNER }));
vi.mock("next/server", () => ({ after: vi.fn() }));
vi.mock("workflow/api", () => ({ start: mock.start, getRun: vi.fn() }));
let fixture: Awaited<ReturnType<typeof testDatabase>>;
const reference = Buffer.from("RIFF0000WAVEsynthetic");
const prefix = ownerPrefix(TEST_OWNER);
const ref = { pathname: `references/${prefix}/${sha256(reference)}.wav`, hash: sha256(reference), size: reference.length, seconds: 12 };
const voice: Voice = { id: "voice_index", name: "Synthetic Index", provider: "indextts", providerVoiceId: ref.hash, reference: ref, language: "zh", source: "cloned", createdAt: "2026-09-12T00:00:00Z" };
const args = (key = randomUUID()) => ({ text: "合成验收", voice_id: voice.id, speed: 1.5, idempotency_key: key });
beforeEach(async () => {
  fixture = await testDatabase();
  await fixture.db.query("INSERT INTO voices(owner,id,data) VALUES($1,$2,$3)", [TEST_OWNER, voice.id, voice]);
  vi.stubEnv("AUTH0_OWNER_SUB", TEST_OWNER);
  vi.stubEnv("DEFAULT_VOICE_ID", "voice_test");
  vi.stubEnv("APP_BASE_URL", "http://localhost:3108");
  vi.stubEnv("INDEXTTS_URL", "https://synthetic.modal.run");
  vi.stubEnv("MODAL_PROXY_KEY", "synthetic-key");
  vi.stubEnv("MODAL_PROXY_SECRET", "synthetic-secret");
  vi.stubEnv("FISH_API_KEY", ""); vi.stubEnv("FISH_AUDIO_API_KEY", "");
  vi.stubGlobal("fetch", mock.fetch);
  mock.fetch.mockReset().mockImplementation(async () => Response.json({ status: "queued" }));
  mock.get.mockReset().mockImplementation(async () => ({ stream: new Response(reference).body }));
  mock.put.mockReset().mockResolvedValue({});
  mock.head.mockReset().mockResolvedValue({ size: reference.length, contentType: "audio/wav" });
  mock.start.mockReset().mockResolvedValue({ runId: "synthetic-run" });
});
afterEach(async () => { await fixture.close(); vi.unstubAllEnvs(); vi.unstubAllGlobals(); });
it("queues web IndexTTS without Fish credentials and leaves MCP default alone", async () => {
  await setWebVoice(TEST_OWNER, voice.id);
  const web = await webVoices(TEST_OWNER);
  expect(web.defaultVoiceId).toBe(voice.id);
  expect(web.voices.find((v) => v.id === voice.id)).not.toHaveProperty("reference");
  expect(web.voices.find((v) => v.id === "voice_test")?.available).toBe(false);
  const fish = await createReading({ text: "旧默认", speed: 1, idempotency_key: randomUUID() });
  expect((await fixture.db.query("SELECT voice_id FROM jobs WHERE id=$1", [fish.jobId])).rows[0].voice_id).toBe("voice_test");
  const documentId = fish.documentId;
  const response = await tts(new Request("http://localhost/api/tts", { method: "POST", body: JSON.stringify({ documentId, voiceId: voice.id, speed: 1, idempotencyKey: randomUUID() }) }));
  expect(response.status).toBe(202);
  vi.stubEnv("MODAL_PROXY_SECRET", "");
  const failed = await tts(new Request("http://localhost/api/tts", { method: "POST", body: JSON.stringify({ documentId, voiceId: voice.id, speed: 1, idempotencyKey: randomUUID() }) }));
  expect(failed.status).toBe(503);
  expect((await fixture.db.query("SELECT * FROM jobs")).rows).toHaveLength(2);
});
it("snapshots the reference/model and uses a new cache namespace", async () => {
  const originalInput = args();
  const job = await createReading(originalInput);
  const first = (await fixture.db.query<{ synthesis: unknown; model: string }>("SELECT synthesis,model FROM jobs WHERE id=$1", [job.jobId])).rows[0];
  expect(first.model).toBe(INDEXTTS_MODEL);
  await fixture.db.query("UPDATE voices SET data=$3 WHERE owner=$1 AND id=$2", [TEST_OWNER, voice.id, { ...voice, reference: { ...ref, hash: "b".repeat(64) } }]);
  expect((await createReading(originalInput)).jobId).toBe(job.jobId);
  const claim = await claimNext(job.jobId, TEST_OWNER);
  if (typeof claim === "string") throw new Error("missing claim");
  expect(claim.job.synthesis?.reference?.hash).toBe(ref.hash);
  const next = await queueDocument({ documentId: job.documentId, voiceId: voice.id, speed: 1.5, idempotencyKey: randomUUID() });
  // Reference edits cannot coalesce into a task with different synthesis settings.
  expect(next.jobId).not.toBe(job.jobId);
});
it("polls one durable attempt through transient failures, then publishes private MP3", async () => {
  const job = await createReading(args());
  mock.fetch.mockRejectedValueOnce(new Error("lost response"));
  await generateNext(job.jobId, TEST_OWNER);
  const attempt = (await fixture.db.query("SELECT attempt FROM job_items WHERE job_id=$1", [job.jobId])).rows[0].attempt;
  await fixture.db.query("UPDATE generation_claims SET poll_after=now()-interval '1 second'");
  await generateNext(job.jobId, TEST_OWNER);
  expect(mock.fetch.mock.calls[0][0]).toBe(mock.fetch.mock.calls[1][0]);
  expect((await fixture.db.query("SELECT * FROM indextts_requests")).rows).toHaveLength(1);
  expect(mock.get).toHaveBeenCalledTimes(1);
  expect((await readingStatus(job.jobId)).items[0].status).toBe("working");
  mock.fetch.mockImplementation(async (url: string) => url.endsWith("/audio")
    ? new Response("ID3synthetic", { headers: { "Content-Type": "audio/mpeg" } }) : Response.json({ status: "ready" }));
  await fixture.db.query("UPDATE generation_claims SET poll_after=now()-interval '1 second'");
  await generateNext(job.jobId, TEST_OWNER);
  expect((await readingStatus(job.jobId)).status).toBe("completed");
  expect((await fixture.db.query("SELECT attempt FROM job_items WHERE job_id=$1", [job.jobId])).rows[0].attempt).toBe(attempt);
  expect((await fixture.db.query("SELECT * FROM generation_claims")).rows).toHaveLength(0);
  const repeated = await createReading(args());
  expect(await generateNext(repeated.jobId, TEST_OWNER)).toBe("done");
});
it("rejects cross-owner reference reads before reaching Modal", async () => {
  await fixture.db.query("UPDATE voices SET data=$3 WHERE owner=$1 AND id=$2", [TEST_OWNER, voice.id, { ...voice, reference: { ...ref, pathname: "references/another-owner/recording.wav" } }]);
  await generateNext((await createReading(args())).jobId, TEST_OWNER);
  expect(mock.get).not.toHaveBeenCalled();
  expect(mock.fetch).not.toHaveBeenCalled();
});
it("marks terminal failure and requires explicit retry; expiry keeps uncertain slots", async () => {
  const job = await createReading(args());
  mock.fetch.mockResolvedValueOnce(Response.json({ status: "error" }));
  await generateNext(job.jobId, TEST_OWNER);
  const state = await readingStatus(job.jobId);
  expect(state.items[0].status).toBe("error");
  await retrySegment(job.jobId, state.items[0].segment_id, true, TEST_OWNER);
  await generateNext(job.jobId, TEST_OWNER);
  expect((await fixture.db.query("SELECT * FROM indextts_requests")).rows).toHaveLength(2);
  await fixture.db.query("UPDATE generation_claims SET expires_at=now()-interval '1 second'");
  await generateNext(job.jobId, TEST_OWNER);
  expect((await readingStatus(job.jobId)).items[0].status).toBe("uncertain");
  expect((await fixture.db.query("SELECT * FROM generation_claims")).rows).toHaveLength(1);
});
it("recovery skips unconfigured Fish tasks and dispatches IndexTTS", async () => {
  await createReading({ text: "旧 Fish", speed: 1, idempotency_key: randomUUID() });
  const index = await createReading(args());
  expect(await recoverDispatches()).toBe(1);
  expect(mock.start).toHaveBeenCalledTimes(1);
  expect(mock.start.mock.calls[0][1]).toEqual([index.jobId, TEST_OWNER]);
});
it("registers a private reference once and sets only the web default", async () => {
  mock.fetch.mockImplementation(async () => new Response(reference, { headers: { "X-Audio-Seconds": "12" } }));
  const upload = await reserveUpload({ contentType: "audio/wav", size: reference.length }, TEST_OWNER);
  const input = { provider: "indextts" as const, name: "Synthetic reference", language: "zh" as const, consent: true as const, uploadIds: [upload.id], idempotencyKey: randomUUID(), makeDefault: true };
  const registered = await registerReferenceVoice(input, TEST_OWNER);
  expect(await registerReferenceVoice(input, TEST_OWNER)).toEqual(registered);
  expect(mock.fetch).toHaveBeenCalledTimes(1);
  expect((await webVoices(TEST_OWNER)).defaultVoiceId).toBe(registered.id);
  expect(process.env.DEFAULT_VOICE_ID).toBe("voice_test");
  await expect(registerReferenceVoice({ ...input, name: "Changed" }, TEST_OWNER)).rejects.toMatchObject({ status: 409 });
  await expect(registerReferenceVoice({ ...input, idempotencyKey: randomUUID() }, "another-owner")).rejects.toMatchObject({ status: 422 });
});
it("rejects unsafe Modal destinations and invalid normalized recordings", async () => {
  vi.stubEnv("INDEXTTS_URL", "https://attacker.test");
  expect(() => indexTtsConfig()).toThrow();
  vi.stubEnv("INDEXTTS_URL", "https://synthetic.modal.run");
  mock.fetch.mockResolvedValueOnce(new Response("invalid", { headers: { "X-Audio-Seconds": "12" } }));
  const upload = await reserveUpload({ contentType: "audio/wav", size: reference.length }, TEST_OWNER);
  await expect(registerReferenceVoice({ provider: "indextts", name: "Synthetic", language: "zh", consent: true, uploadIds: [upload.id], idempotencyKey: randomUUID(), makeDefault: true }, TEST_OWNER)).rejects.toMatchObject({ status: 502 });
  expect((await fixture.db.query("SELECT * FROM clone_requests")).rows).toHaveLength(0);
  expect(mock.put).not.toHaveBeenCalled();
});
